FROM alpine:3.4

RUN apk add --update openssh-client git tar wget
RUN wget https://github.com/mholt/caddy/releases/download/v0.9-beta.2/caddy_linux_amd64.tar.gz
RUN tar -xz caddy_linux_amd64.tar.gz

COPY src/Caddyfile /etc/Caddyfile

EXPOSE 80 443 2015
ENTRYPOINT ["/usr/bin/caddy"]
CMD ["--conf", "/etc/Caddyfile"]
